### PR TITLE
Adding Message() hints

### PR DESCRIPTION
**Pull request by chrisbolin**
The Message object can save users a ton of time, so putting it in the docs might help

### CODE REVIEW

**Comment by Slava** [comment]
thanks!

**Comment by chrisbolin** [comment]
you're welcome. thanks for making the package - saved me a lot of work :P

**Comment by Slava** [comment]
No problem! Glad somebody found a good use of it. For one, I never reached a project where this would be useful, I gave up after building all the GMail stuff. Let me know if you use it in any commercial product, that would be interesting.

**Comment by chrisbolin** [comment]
That’s the idea. I’ll let you know

**Pull request merged**
